version: "3"
services:
  employee-status:
    image: employee-status-image
    ports:
      - "8081:8080"
    networks:
      - employee-status-network2
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - employee-status-network2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retaildb
networks:
  employee-status-network2: